blueprint:
  name: APP应用短信通知
  description: "模板内包含变量  短信消息：{{text}}，发送号码：{{from}}"
  domain: automation
  source_url: https://github.com/shaonianzhentan/ha_app/blob/main/blueprints/ha_app_sms.yaml
  input:
    other:
      name: 其它消息
      description: 没有匹配到定义消息时，执行此服务
      default: []
      selector:
        action: {}
    express:
      name: 快递消息
      description: 快递收件码短信消息
      default: []
      selector:
        action: {}
    captcha:
      name: 验证码
      description: 验证码短信消息
      default: []
      selector:
        action: {}
    wechat_payment:
      name: 微信支付
      description: 微信支付短信消息
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: ha_app
  event_data:
    type: sms
action:
- variables:
    text: '{{ trigger.event.data.data.content }}'
    from: '{{ trigger.event.data.data.from }}'
- choose:
  - conditions:
    - '{{ "菜鸟驿站" in text }}'
    - '{{ "兔喜生活" in text }}'
    sequence: !input express
  - conditions:
    - '{{ "验证码" in text }}'
    sequence: !input captcha
  - conditions:
    - '{{ "微信支付" in text }}'
    sequence: !input wechat_payment
  - conditions:
    - '{{ text != "" }}'
    sequence: !input other