blueprint:
  name: APP应用通知按钮操作
  description: 
  domain: automation
  source_url: https://github.com/shaonianzhentan/ha_app/blob/main/blueprints/ha_app_action.yaml
  input:
    test:
      name: 示例
      description: 没有匹配到应用时，执行此服务
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: ha_app
  event_data:
    type: action
action:
- variables:
    action: '{{ trigger.event.data.data }}'
- choose:
  - conditions:
    - '{{ action == "test" }}'
    sequence: !input test