blueprint:
  name: APP应用通知消息
  description: "模板内包含变量  标题：{{title}}  内容：{{content}}  短文本：{{text}}  应用包：{{package}}"
  domain: automation
  source_url: https://github.com/shaonianzhentan/ha_app/blob/main/blueprints/ha_app_notify.yaml
  input:
    other:
      name: 其它应用
      description: 没有匹配到应用时，执行此服务
      default: []
      selector:
        action: {}
    com_xiaomi_smarthome:
      name: 米家
      description: com.xiaomi.smarthome
      default: []
      selector:
        action: {}
    com_tencent_mm:
      name: 微信
      description: com.tencent.mm
      default: []
      selector:
        action: {}
    com_tencent_mobileqq:
      name: QQ
      description: com.tencent.mobileqq
      default: []
      selector:
        action: {}
    com_coolkit:
      name: 易微联
      description: com.coolkit
      default: []
      selector:
        action: {}
    com_byd_aeri_caranywhere:
      name: 比亚迪
      description: com.byd.aeri.caranywhere
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: ha_app
  event_data:
    type: notify
action:
- variables:
    package: '{{ trigger.event.data.data.package }}'
    title: '{{ trigger.event.data.data.title }}'
    content: '{{ trigger.event.data.data.content }}'
    text: '{{ trigger.event.data.data.text }}'
- choose:
  - conditions:
    - '{{ package == "com.xiaomi.smarthome" }}'
    sequence: !input com_xiaomi_smarthome
  - conditions:
    - '{{ package == "com.tencent.mm" }}'
    sequence: !input com_tencent_mm
  - conditions:
    - '{{ package == "com.tencent.mobileqq" }}'
    sequence: !input com_tencent_mobileqq
  - conditions:
    - '{{ package == "com.coolkit" }}'
    sequence: !input com_coolkit
  - conditions:
    - '{{ package == "com.byd.aeri.caranywhere" }}'
    sequence: !input com_byd_aeri_caranywhere
  - conditions:
    - '{{ package != "" }}'
    sequence: !input other